language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
env:
  global:
  - FRAMEWORK_NAME=SwiftySQL
before_install:
- rvm get head
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
script:
- sh scripts/ci.sh
